### ISSUE TITLE
-bash: standard-readme: command not found

### ISSUE THREAD

**Issue by lukasoppermann** [RichardLitt/standard-readme-cli#3]
Hey,

I installed it using npm and now I am getting this:

> -bash: standard-readme: command not found

`npm -g list` shows: `standard-readme@2.0.0`

Where did I screw up? Any ideas? Installed it globally like suggested. Thanks, appreciate the whole standard-readme effort. 👍

**Comment by RichardLitt** [comment]
You didn't screw up; I should have stated that this was a WIP. I have now done so. This issue should also be closed - I have removed the bin in [generator-standard-readme](https://github.com/RichardLitt/generator-standard-readme) - see https://github.com/RichardLitt/generator-standard-readme/issues/26.

**Comment by RichardLitt** [comment]
Also, thank you! And man, you are fast.

**Comment by lukasoppermann** [comment]
Was at berlinjs. 😄 👍

**Comment by RichardLitt** [comment]
The day after I worked on this with @wooorm. Lots more to do. :)
